[mysql]
host = "maroonlinedb.cmz604qwqzvi.us-east-1.rds.amazonaws.com"
user = "admin"
password = "ch00ch00!"
database = "maroonlinedb"

[cta]
api_key = "8e6648bdf10240f082b11ab99cfa38ba"

[email]
sender_password = "jddckesshligbhlg"